# Generated by Django 6.0.2 on 2026-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_quantity_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
